PRICE_LOW = 0
PRICE_MED = 1
PRICE_HIGH = 2

LUG_SMALL = 3
LUG_MED = 4
LUG_BIG = 5

SAFE_LOW = 6
SAFE_MED = 7
SAFE_HIGH = 8

ACCEPT = 9
NOT_ACCEPT = 10

data = [[PRICE_LOW,  LUG_MED,   SAFE_MED,  ACCEPT],
        [PRICE_LOW,  LUG_MED,   SAFE_HIGH, ACCEPT],
        [PRICE_LOW,  LUG_SMALL, SAFE_MED,  ACCEPT],
        [PRICE_MED,  LUG_SMALL, SAFE_MED,  ACCEPT],
        [PRICE_MED,  LUG_BIG,   SAFE_HIGH, ACCEPT],
        [PRICE_HIGH, LUG_SMALL, SAFE_HIGH, ACCEPT],
        [PRICE_LOW,  LUG_BIG,   SAFE_HIGH, ACCEPT],
        [PRICE_HIGH, LUG_MED,   SAFE_MED,  ACCEPT],
        [PRICE_MED,  LUG_MED,   SAFE_MED,  ACCEPT],
        [PRICE_MED,  LUG_BIG,   SAFE_MED,  ACCEPT],
        [PRICE_LOW,  LUG_BIG,   SAFE_MED,  NOT_ACCEPT],
        [PRICE_HIGH, LUG_BIG,   SAFE_HIGH, NOT_ACCEPT],
        [PRICE_LOW,  LUG_SMALL, SAFE_MED,  NOT_ACCEPT],
        [PRICE_MED,  LUG_MED,   SAFE_HIGH, NOT_ACCEPT],
        [PRICE_MED,  LUG_BIG,   SAFE_LOW,  NOT_ACCEPT],
        [PRICE_LOW,  LUG_MED,   SAFE_LOW,  NOT_ACCEPT],
        [PRICE_LOW,  LUG_SMALL, SAFE_LOW,  NOT_ACCEPT],
        [PRICE_MED,  LUG_MED,   SAFE_MED,  NOT_ACCEPT],
        [PRICE_MED,  LUG_MED,   SAFE_LOW,  NOT_ACCEPT],
        [PRICE_MED,  LUG_SMALL, SAFE_LOW,  NOT_ACCEPT],
        [PRICE_MED,  LUG_BIG,   SAFE_MED,  NOT_ACCEPT],
        [PRICE_HIGH, LUG_BIG,   SAFE_MED,  NOT_ACCEPT],
        [PRICE_HIGH, LUG_BIG,   SAFE_LOW,  NOT_ACCEPT],
        [PRICE_HIGH, LUG_SMALL, SAFE_LOW,  NOT_ACCEPT],
        [PRICE_HIGH, LUG_SMALL, SAFE_MED,  NOT_ACCEPT]]